import boto3 
from langchain.prompts import ChatPromptTemplate, MessagesPlaceholder
from langchain_core.messages import HumanMessage, AIMessage
from langchain_openai import ChatOpenAI
import pandas as pd
from botocore.exceptions import ClientError
from botocore.config import Config
from prompts import SYSTEM_PROMPT
from pathlib import Path
import datetime
from dotenv import load_dotenv

def get_inference_profile_arn(model):
    """
    Get the inference profile ARN for the specified model.
    
    Args:
        model (str): The name of the model's inference profile.
        
    Returns:
        str: The ARN of the inference profile.
    """
    try:
        client = boto3.client(service_name="bedrock", 
                              region_name="us-east-1")
        response = client.list_inference_profiles()
    except ClientError as e:
        print(f"Error accessing inference profiles using Bedrock client: {e}")
        return 
    
    inf_profile = next( 
        (
            ele['inferenceProfileArn'] 
            for ele in response['inferenceProfileSummaries'] 
            if ele['inferenceProfileName'] == model), 
        None
    )
    
    return inf_profile


def generate_conversation(bedrock_client, model_id, messages, system_prompt):
    """
    Generate a conversation response from the LLM model using the Bedrock Converse API.
    
    Args:
        bedrock_client: The Bedrock runtime client.
        model_id: The ID of the model to use for generating the conversation.
        messages: The list of messages in the conversation history.
        system_prompt: The system prompt to guide the model's responses.
    
    Returns:
        The response from the model generated by the Converse API.
    """

    try: 
        response = bedrock_client.converse(
            modelId=model_id,
            messages=messages,
            system=system_prompt
        )
    except Exception as e:
        print(f"Error invoking Converse API: {e}")
        raise

    return response


def get_queries(q_type):
    """
    Get user queries based on the specified question type.

    Args:
        q_type (str): The type of question to filter queries.

    Returns:
        pd.DataFrame: A DataFrame containing the filtered queries.
    """

    # Read file containing all zoning related queries
    file_path = Path.cwd().parent / "temp" / "zoning-code-questions.csv"
    all_queries = pd.read_csv(file_path)

    # Filter queries for relevant question type
    queries = all_queries.loc[all_queries['index'].str.contains(q_type)]

    return queries


def get_user_queries_with_context(q_type, embedding_vs, k):
    """
    Get user queries along with their context from the embedding vector store.

    Args:
        q_type (str): The type of question to filter queries.
        embedding_vs: The embedding vector store.
        k (int): The number of top context documents to retrieve.

    Returns:
        pd.DataFrame: A DataFrame containing the queries with their context.
    """

    # Get user queries based on question type
    queries = get_queries(q_type)

    # Define columns
    queries['query_w_context'] = None
    queries['context_metadata'] = None

    for i in range(k):
        queries[f'context_doc_{i+1}'] = None

    # For each query
    for idx, row in queries.iterrows():

        # Retrieve top-k context from the vector store based on the user query
        top_k_context = get_top_k_context_metadata(embedding_vs, row['question'], k)
       
        # Combine question and context to create user message
        context_docs = ""
        context_metadata = {}
        
        for i, doc in enumerate(top_k_context):
            # Combine retrieved context
            context_docs += f"Context {i+1}: {doc.page_content} \n"
            # Collect context metadata
            context_metadata[f"Context {i+1}"] = doc.metadata
            # Add individual context doc to a column
            queries.at[idx, f'context_doc_{i+1}'] = doc.page_content.strip()
        
        queries.at[idx, 'query_w_context'] = f"Question: {row['question']} \nContext:\n\n {context_docs}"
        queries.at[idx, 'all_context_docs'] = context_docs
        queries.at[idx, 'context_metadata'] = context_metadata

    return queries


def get_top_k_context_metadata(emb_vs, query, k):
    """
    Retrieve the top-k context documents from the embedding vector store based on the user query.

    Args:
        emb_vs: The embedding vector store.
        query (str): The user query.
        k (int): The number of top context documents to retrieve.

    Returns:
        List[Document]: A list of the top-k context documents.
    """
    # Retrieve context from the vector store based on the user query
    top_k_context = emb_vs.similarity_search(query, k)

    return top_k_context
    

def run_conversation(model, q_type, emb_name, emb_vs, folder_path, k=6, n_iter=3):
    """
    Run a conversation loop with the specified model, question type, and embedding vector store, 
    and save the results to a CSV file.

    Args:
        model (str): The name of the model's inference profile.
        q_type (str): The type of question to filter queries.
        emb_name (str): The name of the embedding model used for context retrieval.
        emb_vs: The embedding vector store used for retrieving context.
        folder_path: The path to the folder where the output CSV file will be saved.
        k (int): The number of top context documents to retrieve for each query.
        n_iter (int): The number of conversation iterations to run.
    """
    
    # Connect to Bedrock runtime
    try:
        config = Config(
            read_timeout=120    # Timeout for reading data from the connection
        )
        bedrock_client = boto3.client(service_name="bedrock-runtime", 
                              region_name="us-east-1", config=config)
    except ClientError as e:
        print(f"Error creating Bedrock client: {e}")
        return
        
    # Get the model's inference profile
    inf_profile = get_inference_profile_arn(model)

    # Choose model id based on if inference profile is required or not
    model_id = model if inf_profile is None else inf_profile
    
    # Get user questions and respective context
    queries = get_user_queries_with_context(q_type, emb_vs, k)
    
    # Define columns 
    queries['model'] = model
    queries['execution_date'] = datetime.date.today()
    queries['embedding_model'] = emb_name
    
    # Set up system prompt
    system_prompt = [{"text": SYSTEM_PROMPT}]

    all_iterations = pd.DataFrame()

    for i in range(n_iter):
        # Clear response and update iteration for current run
        queries['iteration'] = i+1
        queries['response'] = None
        queries['reasoning'] = None

        print(f"Conversation iteration {i+1}")
        # Clear messages for current iteration
        messages = []
        
        for idx, row in queries.iterrows():
    
            # Add current message to history
            current_message = {
                "role": "user",
                "content": [{"text": row['query_w_context']}]
            }
            messages.append(current_message)
            
            try: 
                # Get model response for current message using Converse API
                response = generate_conversation(bedrock_client, model_id, messages, system_prompt)
            except Exception as e:
                print(f"Error occurred while generating conversation with Converse API: {e}")

                if "read timeout" in str(e).lower():
                    print("Retrying conversation with a different AWS region.")

                    try: 
                        # Set bedrock client with different region
                        bedrock_client = boto3.client(service_name="bedrock-runtime", 
                                  region_name="us-east-2", config=config)
                        
                        # Get model response for current message using Converse API
                        response = generate_conversation(bedrock_client, model_id, messages, system_prompt)
                        
                    except Exception as er:
                        print(f"Retry failed: {er}")
                        return None
                else:  
                    return
    
            # Extract model's response and append to history
            output_message = response['output']['message']
            messages.append(output_message)
    
            # Save model's response
            if "gpt" in model_id:
                queries.at[idx, 'response'] = output_message['content'][1]['text']
                queries.at[idx, 'reasoning'] = output_message['content'][0]['reasoningContent']['reasoningText']['text']
            else:
                queries.at[idx, 'response'] = output_message['content'][0]['text']
    
            # Print current conversation 
            # print(f"Role: user\nQuestion: {row['question']}")
            # print(f"Role: assistant\nResponse: {output_message['content'][0]['text']}")

        # Store copy of current iteration results
        all_iterations = pd.concat([all_iterations, queries.copy()], ignore_index=True)

    current_date = datetime.date.today().strftime("%Y-%m-%d")
    file_path = folder_path / f"output_{q_type}_{current_date}.csv"
    all_iterations.to_csv(file_path)


def rag_with_openai(model_id, q_type, emb_name, emb_vs, folder_path, k=6, n_iter=3):
    """
    Run a RAG conversation loop using an OpenAI model through LangChain, with the specified question type 
    and embedding vector store, and save the results to a CSV file.

    Args:
        model_id (str): The ID of the OpenAI model to use for generating the conversation
        q_type (str): The type of question to filter queries.
        emb_name (str): The name of the embedding model used for context retrieval.
        emb_vs: The embedding vector store used for retrieving context.
        folder_path: The path to the folder where the output CSV file will be saved.
        k (int): The number of top context documents to retrieve for each query.
        n_iter (int): The number of conversation iterations to run.
    """

    # Load OpenAI API key and initialize a model
    load_dotenv(override=True)
    
    llm = ChatOpenAI(
        model=model_id,
    )
    
    # Set up system prompt
    qa_prompt = ChatPromptTemplate.from_messages([
        ("system", SYSTEM_PROMPT),
        MessagesPlaceholder("chat_history"),
        ("human", "{question}")
    ])

    # Create question and answer chain
    qa_chain = qa_prompt | llm

    # Get user questions and respective context
    queries = get_user_queries_with_context(q_type, emb_vs, k)
    
    # Define columns 
    queries['model'] = model_id
    queries['execution_date'] = datetime.date.today()
    queries['embedding_model'] = emb_name
    
    all_iterations = pd.DataFrame()

    for i in range(n_iter):
        # Clear response and update iteration for current run
        queries['iteration'] = i+1
        queries['response'] = None

        print(f"Conversation iteration {i+1}")
        # Clear messages for current iteration
        chat_history = []
        
        for idx, row in queries.iterrows():
            try: 
                # Get OpenAI model response for current message 
                response = qa_chain.invoke({
                                "context": row['all_context_docs'],
                                "chat_history": chat_history,
                                "question": row['question']
                            })
            except Exception as e:
                print(f"Error occurred while generating conversation with OpenAI: {e}")
                return

            # Add current query to history
            chat_history.append(HumanMessage(content = row['question']))
            
            # Extract model's response and append to history
            chat_history.append(AIMessage(content = response.content))
    
            # Save model's response
            queries.at[idx, 'response'] = response.content
    
        # Store copy of current iteration results
        all_iterations = pd.concat([all_iterations, queries.copy()], ignore_index=True)

    current_date = datetime.date.today().strftime("%Y-%m-%d")
    file_path = folder_path / f"output_{q_type}_{current_date}.csv"
    all_iterations.to_csv(file_path)
    